version: '3.8'
services:
  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
      - 5173:5173